### ISSUE TITLE
Better GitLab support

### ISSUE THREAD

**Issue by jaraco** [coherent-oss/system#18]
In https://gitlab.com/warsaw/flufl.enum/-/tree/coherent?ref_type=heads, I'm exploring applying the coherent system to [flufl.enum](https://pypi.org/project/flufl.enum) with @warsaw.

In [warsaw/flufl.enum!17](https://gitlab.com/warsaw/flufl.enum/-/merge_requests/17), I'm refreshing that work.

In https://github.com/coherent-oss/system/commit/e64683b4dc6085140ea5d034e1f301a19fa9c291, I started work on implementing a GitLab CI common config. Unlike GitHub, GitLab provides a very nice "include" mechanism, so it's [pretty straightforward](https://gitlab.com/warsaw/flufl.enum/-/commit/136f3abca0c94b2b7dc28764a0815bfede4e5316?merge_request_iid=17) to implement derivative workflows.

Implementing that integration, however, revealed that the reliance on GitHub and the `gh` command in the metadata discovery does lead to [failures](https://gitlab.com/jaraco/flufl.enum/-/jobs/7900091650).

- [x] https://github.com/coherent-oss/coherent.build/issues/5

**Comment by jaraco** [comment]
While thinking about this issue, I'm also wondering if there's a more symmetric way to define the workflows. Currently, GitHub workflows are defined at `system/.github/workflows/main.yml` and GitLab workflows are at `system/gitlab-common.yml`. I wonder if the location of reusable workflows requires they be in `.github/workflows` or if they could be placed in a common structure, something like:

```
system
└── CI
    ├── GitHub
    │   └── common.yml
    └── GitLab
        └── common.yml
```

I'm confident that would work for GitLab, as the derivative workflows simply reference the included workflow by URL.

**Comment by jaraco** [comment]
After addressing coherent-oss/coherent.build#5, there's a new failure:

```
      fatal: detected dubious ownership in repository at '/builds/jaraco/flufl.enum'
      To add an exception for this directory, call:
      
          git config --global --add safe.directory /builds/jaraco/flufl.enum
```

I saw something about this in the workflow definition from which I sourced this one. I must have removed the workaround when trimming out other details.

**Comment by jaraco** [comment]
> I wonder if the location of reusable workflows requires they be in `.github/workflows` or if they could be placed in a common structure

I confirmed that [GitHub specifies](https://docs.github.com/en/actions/sharing-automations/reusing-workflows#creating-a-reusable-workflow) that called workflows be in the `.github/workflows` directory.

**Comment by jaraco** [comment]
GitLab support is now adequate.

**Comment by warsaw** [comment]
Very cool @jaraco !  I'm not sure when I'll have time to give this a shot, since this and my other libraries are pretty stable at this point.  Likely when Python 3.14 is a thing and I want to add support for that, and deprecate/remove 3.8.

**Comment by jaraco** [comment]
Note this MR is only for the branch, so I’d recommend to merge without delay… and we can consider merging into main later.

Sent from my comm

On Sep 24, 2024, at 16:21, Barry Warsaw ***@***.***> wrote:

﻿

Very cool @jaraco<https://github.com/jaraco> ! I'm not sure when I'll have time to give this a shot, since this and my other libraries are pretty stable at this point. Likely when Python 3.14 is a thing and I want to add support for that, and deprecate/remove 3.8.
