### ISSUE TITLE
Identify a way to share GitHub workflows

### ISSUE THREAD

**Issue by jaraco** [coherent-oss/system#2]
As part of coherent-oss/system#1, I'd like to find a way to do continuous integration without having to copy large amounts of boilerplate into every project. It does appear at first blush as if [reusable workflows](https://docs.github.com/en/actions/using-workflows/reusing-workflows) may do most of that. Here's what I'm imagining:

A repo like `coherent-oss/workflows` would contain `.github/workflows/main.yml` with [contents similar to that file in skeleton](https://github.com/jaraco/skeleton/blob/main/.github/workflows/main.yml), including the matrix.

And each coherent system project would have a small file with not much more than:

```
jobs:
  upstream:
    uses: coherent-oss/workflows/.github/workflows/main.yml
```

Then, the workflow could be centrally maintained to limit the amount of toil in maintaining the common workflow.

Bonus features could include:

- add a feature to GitHub so that the calling workflow doesn't have to exist (maybe configured in settings)
- have the build matrix automatically generated by supported Python versions (this could happen by automated commits or pull requests to the workflows repo)

**Comment by jaraco** [comment]
One major problem with re-usable workflows might be lack of support for trusted publishing (https://github.com/pypi/warehouse/issues/11096). That doesn't have to block this effort, however.

**Comment by pawamoy** [comment]
There's a way to generate the test matrix dynamically. We could do like coherent-build and query Python's website to get all active versions, then build the Matrix with the result. I can try to show an example later.

**Comment by bswck** [comment]
First issue I ran into is permission conflicts in multi-job workflows.
Perhaps we'll end up splitting workflows and setting top-level `permissions` for each downstream workflow requesting one job from a reusable workflow.

https://github.com/dummy-coherent-org/project/actions/runs/9811456360/workflow

**Comment by jaraco** [comment]
Is there a reason `<org>` needs to be the same for the `<workflows repo>` and the `<project>`? Can a project like `jaraco/tempora` reference `coherent-oss/workflows`?

**Comment by jaraco** [comment]
I see the permission error is:

```
The workflow is not valid. .github/workflows/main.yml (Line: 14, Col: 3): Error calling workflow 'dummy-coherent-org/workflows/.github/workflows/main.yml@main'. The nested job 'release' is requesting 'contents: write', but is only allowed 'contents: read'.
```

Feel free to either drop the release workflow (for now) or reduce the security on the upstream workflow definition until you get something working.

**Comment by bswck** [comment]
> Is there a reason `<org>` needs to be the same for the `<workflows repo>` and the `<project>`? Can a project like `jaraco/tempora` reference `coherent-oss/workflows`?

Definitely not a single one I could think of! Thanks for bringing this up.

**Comment by jaraco** [comment]
My hope in early stages is to get `coherent.build` and `coherent.test` to run their tests (one matrix of jobs) against a common workflow. My next goal would be to see if [`tempora@experiment/coherent`](https://github.com/jaraco/tempora/tree/experiment/coherent) can use the same workflows. Later we can expand to see if other features can be incorporated.

**Comment by bswck** [comment]
After removing the write permissions from the release job, I managed to get the workflow running on an empty repo:
https://github.com/dummy-coherent-org/project/actions/runs/9815868216

All of these jobs assume an empty `tox.ini`. The calling workflow should check out the repository with the necessary configuration files.

So... get them from `(meta)/` and secondarily from the workflow repo?

**Comment by bswck** [comment]
It would make sense to store `tox.ini` together with the workflow in the same repository.

The workflows repository should now maybe be instead called "ancillary"?

**Comment by bswck** [comment]
As I'm writing, I must underline the thought that the ancillary repos should have some kind of self-tests to check if the workflows are working the way they're supposed to.

**Comment by bswck** [comment]
It would also be cool if `coh install` was aware of the ancillary repo to install the necessary CQA tools.

**Comment by jaraco** [comment]
> The workflows repository should now maybe be instead called "ancillary"?

We can use `system`, since these are the ancillary concerns managed by the coherent system.

**Comment by jaraco** [comment]
Sorry I haven't checked in on this in a while. It's the issue I care about the most, as it's the main thing blocking me adopting this for small projects. What is the status? I seem to recall having seen everything passing except maybe diffcov. I'm happy to drop diffcov if that's a blocker.

Also, I'm not sure we have to use tox. Tox is just one tool for orchestrating builds. It's conceivable that the coherent system will merely perform a simplified version of what tox does, using `coh test` to install the dependencies and run the tests.

**Comment by bswck** [comment]
We dropped tox completely. The only blocker now is docs, but we want a framework for building those anyway, so I can remove the docs job from our workflow in this repo and this will be essentially ready.

**Comment by bswck** [comment]
To give things more details, this is how diffcov works currently: https://github.com/jaraco/tempora/actions/runs/10329685084/job/28597773771?pr=34

And this is what docs fail with, currently (tempora experimental branch)
https://github.com/jaraco/tempora/actions/runs/10329685084/job/28597773672?pr=34

**Comment by bswck** [comment]
Looking at the diffcov job run, I'm not entirely sure that it works as it is supposed to. It looks like it only looked to `__init__.py`.

**Comment by bswck** [comment]
> I seem to recall having seen everything passing except maybe diffcov. I'm happy to drop diffcov if that's a blocker.

I'll comment diffcov out. We can keep the docs job, as it has a strong potential to be fixed by a minimal `pyproject.toml`.

**Comment by bswck** [comment]
@jaraco Ready. We could start incorporating the reusable workflows by merging https://github.com/jaraco/tempora/pull/34. Expect a "caller workflow" to be included in the `coh init` command we talked about in coherent-oss/coherent.build#20.
